name: Go

on:
  - push
  - pull_request

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./cli/... ./lib/...

    - name: Test
      run: go test -v ./cli/... ./lib/...

  build:
    strategy:
      matrix:
        - arch: darwin
          on: darwin-latest
        - arch: linux
          on: ubuntu-latest
        - arch: windows
          on: windows-latest
    runs-on: ${{ matrix.on }}
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: ./release.sh ${{ matrix.on }}

    - name: Publish
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        name: Latest
        files: release/archives/*
