name: Go

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./cli/... ./lib/...

    - name: Test
      run: go test -v ./cli/... ./lib/...

    - name: Build all
      run: ./release.sh

    - name: Publish
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        name: Latest
        files: release/archives/*
